### ISSUE TITLE
The movie is loading forever

### ISSUE THREAD

**Issue by TrietPham96** [napthedev/filmhot#2]

**Comment by phongna07** [comment]
The movie source loklok is using http, not https for their api, so there's nothing I can do right now... I don't have money to build a proxy

<img width="589" alt="image" src="https://user-images.githubusercontent.com/74483690/160219802-41386820-36a0-45ed-bc16-531684a11c5f.png">

**Comment by TrietPham96** [comment]
Yes thank you! im understand, so sad to that. I also make a project movie online with nuxt Vuejs, maybe we have to find another resource of film
