### ISSUE TITLE
fix lỗi ko xem đc flm 28/3/2022

### ISSUE THREAD

**Issue by kaitoukid-1412** [napthedev/filmhot#3]
- vấn đề gặp phải: https://github.com/napthedev/filmhot/issues/2

1. fix cứng từ phias client user:

![image](https://user-images.githubusercontent.com/15698245/160432932-8a53f4f6-a75f-4946-a8af-5bfc86cf5264.png)
![image](https://user-images.githubusercontent.com/15698245/160433065-6a132fd4-0b83-43e6-be8b-ecbbbc5c614b.png)
![image](https://user-images.githubusercontent.com/15698245/160433819-cd4e3832-3c34-4c4c-bf10-dd8c97cfc870.png)

2. đừng qên **f5** nếu gặp lỗi cors như này!

![image](https://user-images.githubusercontent.com/15698245/160434359-24e44132-6cf4-4e0c-aac0-4977c5ba08f2.png)

**Comment by phongna07** [comment]
Vẫn là cách chỉnh settings từ phía client một cách tình thế, hiện giờ nguồn phim được leak không hỗ trợ https nên là không có cách nào fix triệt để cả. Đã xài chùa thì chịu thôi
