### ISSUE TITLE
vercel

### ISSUE THREAD

**Issue by titu3e** [napthedev/filmhot#5]
can you help me for deploying it on vercel??

**Comment by phongna07** [comment]
Go to the settings of the project, change the serverless function region to Sydney, Australia and then redeploy. Remember to setup supabase credentials too :v

**Comment by itz-dude** [comment]
> Go to the settings of the project, change the serverless function region to Sydney, Australia and then redeploy. Remember to setup supabase credentials too :v

![image](https://user-images.githubusercontent.com/108194557/185529141-b800a281-3a7c-4172-9c5c-fbbaa255ee72.png)
it shows this in supabase

**Comment by phongna07** [comment]
You can try again with the new guide on the docs, you need to install psql
